
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test folder creation
        run: mkdir test
      - uses: cdssnc/auto-commit-github-action@v2
      
