
name: Painting Update

on:
  workflow_dispatch:

jobs:
  paintings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: mkdir paintings
      - run: npm install
      - name: download paintings
        run: node saveImages.js
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "loaded paintings"
          git push

      
